#include "UE4Header.h"
#include "../libUE4Dumper/UE4Dumper.h"
#include "../libUE4Struct/ilbUE4Struct.h"
#include "../../core/log/log.h"
#include <fstream>
#include <sstream>
#include <vector>
#include <algorithm>
#include <sys/stat.h>

namespace ue4 {

UE4Header::UE4Header(UE4Dumper& dumper, const std::string& outputDir)
    : m_dumper(dumper), m_outputDir(outputDir)
{
}

// ---- 工具函数 ----

std::string UE4Header::cleanIdentifier(const std::string& name) {
    std::string result;
    result.reserve(name.size());
    for (char c : name) {
        if ((c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') ||
            (c >= '0' && c <= '9') || c == '_') {
            result += c;
        } else {
            result += '_';
        }
    }
    return result;
}

std::string UE4Header::escapeJsonString(const std::string& s) {
    std::string result;
    result.reserve(s.size() + 10);
    for (char c : s) {
        switch (c) {
            case '"':  result += "\\\""; break;
            case '\\': result += "\\\\"; break;
            case '\n': result += "\\n"; break;
            case '\r': result += "\\r"; break;
            case '\t': result += "\\t"; break;
            default:   result += c; break;
        }
    }
    return result;
}

// Property 类名前缀 → C 类型映射
static const char* mapPropertyToType(const std::string& propClassName) {
    if (propClassName.size() <= 8) return nullptr;
    std::string base = propClassName.substr(0, propClassName.size() - 8);
    struct { const char* key; const char* val; } map[] = {
        {"Bool", "bool"}, {"Int", "int32_t"}, {"UInt32", "uint32_t"},
        {"Int8", "int8_t"}, {"Int16", "int16_t"}, {"Int64", "int64_t"},
        {"UInt16", "uint16_t"}, {"UInt64", "uint64_t"}, {"Byte", "uint8_t"},
        {"Float", "float"}, {"Double", "double"},
        {"Str", "FString"}, {"Name", "FName"}, {"Text", "FText"},
        {"Object", "void*"}, {"Class", "void*"},
        {"SoftObject", "TSoftObjectPtr"}, {"SoftClass", "TSoftObjectPtr"},
        {"WeakObject", "TWeakObjectPtr"}, {"LazyObject", "void*"},
        {"Interface", "FScriptInterface"},
        {"Struct", "void*"}, {"Array", "TArray"}, {"Map", "TMap"},
        {"Set", "TSet"}, {"Delegate", "FDelegate"},
        {"MulticastDelegate", "FMulticastDelegate"},
        {"MulticastInlineDelegate", "FMulticastDelegate"},
        {"Enum", "uint8_t"},
    };
    for (auto& m : map) {
        if (base == m.key) return m.val;
    }
    return nullptr;
}

// ---- 一键生成 ----

void UE4Header::start() {
    LOG(LOG_LEVEL_INFO, "[UE4Header] 开始生成 IDA 头文件和脚本");
    mkdir(m_outputDir.c_str(), 0777);

    std::string headerPath = m_outputDir + "ue4.h";
    std::string jsonPath   = m_outputDir + "script.json";

    saveToIdaHeader(headerPath);
    saveToScriptJson(jsonPath);

    LOG(LOG_LEVEL_INFO, "[UE4Header] 全部生成完成");
}

// =====================================================================
//  IDA 头文件生成
//  格式: C 风格结构体声明, 字段带偏移注释, 函数声明带地址注释
// =====================================================================

void UE4Header::saveToIdaHeader(const std::string& path) {
    LOG(LOG_LEVEL_INFO, "[UE4Header] 生成 IDA 头文件: %s", path.c_str());

    std::ofstream fout(path, std::ios::out | std::ios::trunc);
    if (!fout.is_open()) {
        LOG(LOG_LEVEL_ERROR, "[UE4Header] 无法创建文件: %s", path.c_str());
        return;
    }

    // 文件头
    fout << "// UE4 IDA Header - Auto-generated by UE4Header\n";
    fout << "// Target: com.tencent.tmgp.pubgmhd (libUE4.so)\n";
    fout << "// libUE4.so Base: 0x" << std::hex << m_dumper.getModuleBase() << std::dec << "\n\n";

    fout << "#ifndef UE4_IDA_HEADER_H\n";
    fout << "#define UE4_IDA_HEADER_H\n\n";

    // IDA 没有 stdint.h, 直接 typedef
    fout << "typedef signed char int8_t;\n";
    fout << "typedef unsigned char uint8_t;\n";
    fout << "typedef signed short int16_t;\n";
    fout << "typedef unsigned short uint16_t;\n";
    fout << "typedef signed int int32_t;\n";
    fout << "typedef unsigned int uint32_t;\n";
    fout << "typedef signed long long int64_t;\n";
    fout << "typedef unsigned long long uint64_t;\n\n";

    fout << "#pragma pack(push, 1)\n\n";

    // 基础类型定义 (纯 C, IDA 兼容)
    fout << "typedef void(*UE4FunctionPointer)();\n\n";
    fout << "struct FName { int32_t ComparisonIndex; int32_t Number; };\n";
    fout << "struct FString { void* Data; int32_t Num; int32_t Max; };\n";
    fout << "struct FText { char _data[0x18]; };\n";
    fout << "struct TArray { void* Data; int32_t Num; int32_t Max; };\n";
    fout << "struct TMap { char _data[0x50]; };\n";
    fout << "struct TSet { char _data[0x50]; };\n";
    fout << "struct TWeakObjectPtr { int32_t ObjectIndex; int32_t ObjectSerialNumber; };\n";
    fout << "struct TSoftObjectPtr { char _data[0x28]; };\n";
    fout << "struct FDelegate { void* Object; FName FunctionName; };\n";
    fout << "struct FMulticastDelegate { TArray InvocationList; };\n";
    fout << "struct FScriptInterface { void* ObjectPointer; void* InterfacePointer; };\n";
    fout << "struct UObject;\n";
    fout << "struct UClass;\n\n";

    // 收集所有类型
    struct TypeCtx {
        UE4Dumper* dumper;
        std::vector<uintptr_t> classes;
        std::vector<uintptr_t> structs;
        std::vector<uintptr_t> enums;
    };
    TypeCtx ctx;
    ctx.dumper = &m_dumper;

    m_dumper.forEachUObject(m_dumper.getGUObjectArray(),
        [](uintptr_t objPtr, int, void* ud) {
            auto* c = reinterpret_cast<TypeCtx*>(ud);
            std::string cn = c->dumper->readClassName(objPtr);
            if (cn == "Class") c->classes.push_back(objPtr);
            else if (cn == "ScriptStruct") c->structs.push_back(objPtr);
            else if (cn == "Enum" || cn == "UserDefinedEnum") c->enums.push_back(objPtr);
        }, &ctx);

    LOG(LOG_LEVEL_INFO, "[UE4Header] 类型数量: Class=%zu ScriptStruct=%zu Enum=%zu",
        ctx.classes.size(), ctx.structs.size(), ctx.enums.size());

    // ── 前向声明 ──
    fout << "// ===========================================================\n";
    fout << "// Forward Declarations\n";
    fout << "// ===========================================================\n\n";

    for (auto objPtr : ctx.classes) {
        std::string name = cleanIdentifier(m_dumper.readObjectFName(objPtr));
        fout << "struct " << name << ";\n";
    }
    for (auto objPtr : ctx.structs) {
        std::string name = cleanIdentifier(m_dumper.readObjectFName(objPtr));
        fout << "struct " << name << ";\n";
    }
    fout << "\n";

    // ── 枚举 ──
    fout << "// ===========================================================\n";
    fout << "// Enums\n";
    fout << "// ===========================================================\n\n";

    for (auto objPtr : ctx.enums) {
        auto* uenum = reinterpret_cast<UEnum*>(objPtr);
        std::string name = cleanIdentifier(m_dumper.readObjectFName(objPtr));

        fout << "enum " << name << " {\n";
        if (uenum->Names.Data && uenum->Names.Num > 0 && uenum->Names.Num < 10000) {
            for (int i = 0; i < uenum->Names.Num; i++) {
                auto& pair = uenum->Names.Data[i];
                std::string eName = m_dumper.fnameToString(pair.Name.ComparisonIndex, pair.Name.Number);
                fout << "    " << cleanIdentifier(eName) << " = " << (int)pair.Value;
                if (i + 1 < uenum->Names.Num) fout << ",";
                fout << "\n";
            }
        }
        fout << "};\n\n";
    }

    // ── ScriptStruct ──
    fout << "// ===========================================================\n";
    fout << "// ScriptStructs (Fields)\n";
    fout << "// ===========================================================\n\n";

    for (auto objPtr : ctx.structs) {
        auto* structObj = reinterpret_cast<UStruct*>(objPtr);
        std::string name = cleanIdentifier(m_dumper.readObjectFName(objPtr));
        std::string superName;
        if (structObj->SuperStruct) {
            superName = cleanIdentifier(m_dumper.readObjectFName(
                reinterpret_cast<uintptr_t>(structObj->SuperStruct)));
        }

        fout << "// Size: 0x" << std::hex << structObj->PropertiesSize << std::dec << "\n";
        fout << "struct " << name << " {\n";
        if (!superName.empty()) {
            auto* superStruct = reinterpret_cast<UStruct*>(structObj->SuperStruct);
            int superSize = superStruct ? superStruct->PropertiesSize : 8;
            if (superSize <= 0) superSize = 8;
            fout << "    char _base_" << superName << "[0x" << std::hex << superSize << std::dec
                 << "]; /* 0x0 base: " << superName << " */\n";
        }

        // 遍历 Children 链表
        auto* child = reinterpret_cast<UField*>(structObj->Children);
        int depth = 0;
        while (child && depth < 5000) {
            std::string cc = m_dumper.readClassName(reinterpret_cast<uintptr_t>(child));
            if (cc.size() > 8 && cc.substr(cc.size() - 8) == "Property") {
                auto* prop = reinterpret_cast<UProperty*>(child);
                std::string fieldName = cleanIdentifier(
                    m_dumper.readObjectFName(reinterpret_cast<uintptr_t>(child)));
                const char* mappedType = mapPropertyToType(cc);
                std::string typeName = mappedType ? mappedType : cc.substr(0, cc.size() - 8);

                fout << "    " << typeName << " " << fieldName << "; /* 0x"
                     << std::hex << prop->Offset_Internal << std::dec
                     << " Size: 0x" << std::hex << prop->ElementSize << std::dec << " */\n";
            }
            child = child->Next;
            depth++;
        }
        fout << "};\n\n";
    }

    // ── Classes ──
    fout << "// ===========================================================\n";
    fout << "// Classes\n";
    fout << "// ===========================================================\n\n";

    for (auto objPtr : ctx.classes) {
        auto* structObj = reinterpret_cast<UStruct*>(objPtr);
        std::string name = cleanIdentifier(m_dumper.readObjectFName(objPtr));
        std::string superName;
        if (structObj->SuperStruct) {
            superName = cleanIdentifier(m_dumper.readObjectFName(
                reinterpret_cast<uintptr_t>(structObj->SuperStruct)));
        }

        // VTable 结构体 (跳过, 太大会导致 IDA parse_decls 超时)
        // 如需 VTable 信息请查看 dump.cs 中的 VTable 部分

        // 类结构体 (按内存布局, 纯 C 兼容)
        fout << "// Size: 0x" << std::hex << structObj->PropertiesSize << std::dec << "\n";
        fout << "struct " << name << " {\n";

        // 父类内嵌 (用 char 数组避免前向引用问题)
        if (!superName.empty()) {
            auto* superStruct = reinterpret_cast<UStruct*>(structObj->SuperStruct);
            int superSize = superStruct ? superStruct->PropertiesSize : 0x28;
            if (superSize <= 0) superSize = 0x28;
            fout << "    char _base_" << superName << "[0x" << std::hex << superSize << std::dec
                 << "]; /* 0x0 base: " << superName << " */\n";
        } else {
            fout << "    void* _vptr; /* 0x0 */\n";
        }

        // 字段 (只输出本类声明的字段, 按偏移排列)
        auto* child = reinterpret_cast<UField*>(structObj->Children);
        int depth = 0;
        while (child && depth < 5000) {
            std::string cc = m_dumper.readClassName(reinterpret_cast<uintptr_t>(child));
            if (cc.size() > 8 && cc.substr(cc.size() - 8) == "Property") {
                auto* prop = reinterpret_cast<UProperty*>(child);
                std::string fieldName = cleanIdentifier(
                    m_dumper.readObjectFName(reinterpret_cast<uintptr_t>(child)));
                const char* mappedType = mapPropertyToType(cc);
                std::string typeName = mappedType ? mappedType : cc.substr(0, cc.size() - 8);

                fout << "    " << typeName << " " << fieldName << "; /* 0x"
                     << std::hex << prop->Offset_Internal << std::dec
                     << " Size: 0x" << std::hex << prop->ElementSize << std::dec << " */\n";
            }
            child = child->Next;
            depth++;
        }
        fout << "};\n\n";

        // Native 函数声明
        child = reinterpret_cast<UField*>(structObj->Children);
        depth = 0;
        bool hasNativeFunc = false;
        while (child && depth < 5000) {
            if (m_dumper.readClassName(reinterpret_cast<uintptr_t>(child)) == "Function") {
                auto* func = reinterpret_cast<UFunction*>(child);
                if (func->Func && func->FunctionFlags & 0x400) {
                    if (!hasNativeFunc) {
                        fout << "// " << name << " Methods\n";
                        hasNativeFunc = true;
                    }
                    std::string funcName = cleanIdentifier(
                        m_dumper.readObjectFName(reinterpret_cast<uintptr_t>(child)));
                    uintptr_t funcAddr = reinterpret_cast<uintptr_t>(func->Func);
                    uintptr_t offset = funcAddr - m_dumper.getModuleBase();
                    fout << "void " << name << "__" << funcName
                         << "(struct " << name << "* __this); /* RVA: 0x"
                         << std::hex << offset << std::dec << " */\n";
                }
            }
            child = child->Next;
            depth++;
        }
        if (hasNativeFunc) fout << "\n";
    }

    fout << "// ===========================================================\n";
    fout << "// Summary\n";
    fout << "// ===========================================================\n";
    fout << "// Classes: " << ctx.classes.size() << "\n";
    fout << "// ScriptStructs: " << ctx.structs.size() << "\n";
    fout << "// Enums: " << ctx.enums.size() << "\n\n";

    fout << "#pragma pack(pop)\n";
    fout << "#endif // UE4_IDA_HEADER_H\n";
    fout.close();
    LOG(LOG_LEVEL_INFO, "[UE4Header] ✓ IDA 头文件完成: %s", path.c_str());
}

// =====================================================================
//  IDA Script JSON 生成
//  格式: 兼容 Il2CppDumper script.json
// =====================================================================

void UE4Header::saveToScriptJson(const std::string& path) {
    LOG(LOG_LEVEL_INFO, "[UE4Header] 生成 IDA 脚本 JSON: %s", path.c_str());

    std::ofstream fout(path, std::ios::out | std::ios::trunc);
    if (!fout.is_open()) {
        LOG(LOG_LEVEL_ERROR, "[UE4Header] 无法创建文件: %s", path.c_str());
        return;
    }

    // 收集所有 Native UFunction
    struct FuncEntry {
        uintptr_t rva;
        std::string name;
        std::string signature;
    };
    std::vector<FuncEntry> entries;

    struct CollectCtx {
        UE4Dumper* dumper;
        std::vector<FuncEntry>* entries;
    };
    CollectCtx ctx;
    ctx.dumper = &m_dumper;
    ctx.entries = &entries;

    m_dumper.forEachUObject(m_dumper.getGUObjectArray(),
        [](uintptr_t objPtr, int, void* ud) {
            auto* c = reinterpret_cast<CollectCtx*>(ud);
            std::string cn = c->dumper->readClassName(objPtr);
            if (cn != "Class" && cn != "ScriptStruct") return;

            auto* structObj = reinterpret_cast<UStruct*>(objPtr);
            std::string className = c->dumper->readObjectFName(objPtr);

            auto* child = reinterpret_cast<UField*>(structObj->Children);
            int depth = 0;
            while (child && depth < 5000) {
                if (c->dumper->readClassName(reinterpret_cast<uintptr_t>(child)) == "Function") {
                    auto* func = reinterpret_cast<UFunction*>(child);
                    if (func->Func) {
                        uintptr_t funcAddr = reinterpret_cast<uintptr_t>(func->Func);
                        uintptr_t base = c->dumper->getModuleBase();
                        if (funcAddr > base) {
                            std::string funcName = c->dumper->readObjectFName(
                                reinterpret_cast<uintptr_t>(child));

                            FuncEntry e;
                            e.rva = funcAddr - base;
                            e.name = className + "$$" + funcName;
                            e.signature = "void " + UE4Header::cleanIdentifier(className) + "_"
                                        + UE4Header::cleanIdentifier(funcName)
                                        + "(struct " + UE4Header::cleanIdentifier(className) + "* __this);";                            c->entries->push_back(e);
                        }
                    }
                }
                child = child->Next;
                depth++;
            }
        }, &ctx);

    LOG(LOG_LEVEL_INFO, "[UE4Header] 收集到 %zu 个函数", entries.size());

    // 按 RVA 排序
    std::sort(entries.begin(), entries.end(),
        [](const FuncEntry& a, const FuncEntry& b) { return a.rva < b.rva; });

    // 写入 JSON
    fout << "{\n";

    // ScriptMethod
    fout << "  \"ScriptMethod\": [\n";
    for (size_t i = 0; i < entries.size(); i++) {
        fout << "    {\n";
        fout << "      \"Address\": " << entries[i].rva << ",\n";
        fout << "      \"Name\": \"" << escapeJsonString(entries[i].name) << "\",\n";
        fout << "      \"Signature\": \"" << escapeJsonString(entries[i].signature) << "\"\n";
        fout << "    }";
        if (i + 1 < entries.size()) fout << ",";
        fout << "\n";
    }
    fout << "  ],\n";

    // Addresses
    fout << "  \"Addresses\": [\n";
    for (size_t i = 0; i < entries.size(); i++) {
        fout << "    " << entries[i].rva;
        if (i + 1 < entries.size()) fout << ",";
        fout << "\n";
    }
    fout << "  ]\n";

    fout << "}\n";
    fout.close();
    LOG(LOG_LEVEL_INFO, "[UE4Header] ✓ IDA 脚本 JSON 完成: %s (%zu entries)", path.c_str(), entries.size());
}

} // namespace ue4

OBFU_ATTRS_END
