#include "UE5Header.h"
#include "../ilbUE5Dumper/UE5DfmDumper.h"
#include "../ilbUE5Struct/UE5DfmStruct.h"
#include "../../core/log/log.h"
#include <fstream>
#include <sstream>
#include <vector>
#include <algorithm>
#include <cstddef>
#include <sys/stat.h>

namespace ue5dfm {

UE5Header::UE5Header(UE5DfmDumper& dumper, const std::string& outputDir)
    : m_dumper(dumper), m_outputDir(outputDir)
{
}

// ---- 工具函数 ----

std::string UE5Header::cleanIdentifier(const std::string& name) {
    std::string result;
    result.reserve(name.size());
    for (char c : name) {
        if ((c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') ||
            (c >= '0' && c <= '9') || c == '_') {
            result += c;
        } else {
            result += '_';
        }
    }
    return result;
}

std::string UE5Header::escapeJsonString(const std::string& s) {
    std::string result;
    result.reserve(s.size() + 10);
    for (char c : s) {
        switch (c) {
            case '"':  result += "\\\""; break;
            case '\\': result += "\\\\"; break;
            case '\n': result += "\\n"; break;
            case '\r': result += "\\r"; break;
            case '\t': result += "\\t"; break;
            default:   result += c; break;
        }
    }
    return result;
}

// Property 类名前缀 → C 类型映射
static const char* mapPropertyToType(const std::string& propClassName) {
    if (propClassName.size() <= 8) return nullptr;
    std::string base = propClassName.substr(0, propClassName.size() - 8);
    struct { const char* key; const char* val; } map[] = {
        {"Bool", "bool"}, {"Int", "int32_t"}, {"UInt32", "uint32_t"},
        {"Int8", "int8_t"}, {"Int16", "int16_t"}, {"Int64", "int64_t"},
        {"UInt16", "uint16_t"}, {"UInt64", "uint64_t"}, {"Byte", "uint8_t"},
        {"Float", "float"}, {"Double", "double"},
        {"Str", "FString"}, {"Name", "FName"}, {"Text", "FText"},
        {"Object", "void*"}, {"Class", "void*"},
        {"SoftObject", "TSoftObjectPtr"}, {"SoftClass", "TSoftObjectPtr"},
        {"WeakObject", "TWeakObjectPtr"}, {"LazyObject", "void*"},
        {"Interface", "FScriptInterface"},
        {"Struct", "void*"}, {"Array", "TArray"}, {"Map", "TMap"},
        {"Set", "TSet"}, {"Delegate", "FDelegate"},
        {"MulticastDelegate", "FMulticastDelegate"},
        {"MulticastInlineDelegate", "FMulticastDelegate"},
        {"MulticastSparseDelegate", "FMulticastDelegate"},
        {"Enum", "uint8_t"},
    };
    for (auto& m : map) {
        if (base == m.key) return m.val;
    }
    return nullptr;
}

// 读取对象 UClass 的 FName (即 "Class"/"ScriptStruct"/"Enum"/...)
static std::string readObjClassName(const UE5DfmDumper& d, uintptr_t objPtr) {
    uintptr_t cls = UE5DfmDumper::rp(objPtr + offsetof(UObjectBase, ClassPrivate));
    if (!UE5DfmDumper::ok(cls)) return "";
    return d.oname(cls);
}

// ---- 一键生成 ----

void UE5Header::start() {
    LOG(LOG_LEVEL_INFO, "[UE5Header] 开始生成 IDA 头文件和脚本");
    mkdir(m_outputDir.c_str(), 0777);

    std::string headerPath = m_outputDir + "ue5.h";
    std::string jsonPath   = m_outputDir + "script.json";

    saveToIdaHeader(headerPath);
    saveToScriptJson(jsonPath);

    LOG(LOG_LEVEL_INFO, "[UE5Header] 全部生成完成");
}

// =====================================================================
//  IDA 头文件生成
// =====================================================================

void UE5Header::saveToIdaHeader(const std::string& path) {
    LOG(LOG_LEVEL_INFO, "[UE5Header] 生成 IDA 头文件: %s", path.c_str());

    std::ofstream fout(path, std::ios::out | std::ios::trunc);
    if (!fout.is_open()) {
        LOG(LOG_LEVEL_ERROR, "[UE5Header] 无法创建文件: %s", path.c_str());
        return;
    }

    // 文件头
    fout << "// UE5 IDA Header - Auto-generated by UE5Header\n";
    fout << "// Target: com.tencent.tmgp.dfm (libUE4.so, UE 5.4)\n";
    fout << "// libUE4.so Base: 0x" << std::hex << m_dumper.getModuleBase() << std::dec << "\n\n";

    fout << "#ifndef UE5_IDA_HEADER_H\n";
    fout << "#define UE5_IDA_HEADER_H\n\n";

    fout << "typedef signed char int8_t;\n";
    fout << "typedef unsigned char uint8_t;\n";
    fout << "typedef signed short int16_t;\n";
    fout << "typedef unsigned short uint16_t;\n";
    fout << "typedef signed int int32_t;\n";
    fout << "typedef unsigned int uint32_t;\n";
    fout << "typedef signed long long int64_t;\n";
    fout << "typedef unsigned long long uint64_t;\n\n";

    fout << "#pragma pack(push, 1)\n\n";

    // 基础类型定义
    fout << "typedef void(*UE5FunctionPointer)();\n\n";
    fout << "struct FName { int32_t ComparisonIndex; int32_t Number; };\n";
    fout << "struct FString { void* Data; int32_t Num; int32_t Max; };\n";
    fout << "struct FText { char _data[0x18]; };\n";
    fout << "struct TArray { void* Data; int32_t Num; int32_t Max; };\n";
    fout << "struct TMap { char _data[0x50]; };\n";
    fout << "struct TSet { char _data[0x50]; };\n";
    fout << "struct TWeakObjectPtr { int32_t ObjectIndex; int32_t ObjectSerialNumber; };\n";
    fout << "struct TSoftObjectPtr { char _data[0x28]; };\n";
    fout << "struct FDelegate { void* Object; FName FunctionName; };\n";
    fout << "struct FMulticastDelegate { TArray InvocationList; };\n";
    fout << "struct FScriptInterface { void* ObjectPointer; void* InterfacePointer; };\n";
    fout << "struct UObject;\n";
    fout << "struct UClass;\n\n";

    // 收集所有类型 — UE5 使用 getobj(i) 迭代 GUObjectArray
    std::vector<uintptr_t> classes, structs, enums;
    uint32_t numElements = UE5DfmDumper::r32(
        m_dumper.getModuleBase() + m_dumper.getOffGUObjectArrayNum());
    if (numElements == 0 || numElements > 20000000u) {
        LOG(LOG_LEVEL_ERROR, "[UE5Header] 无效的 numElements: %u", numElements);
        fout.close();
        return;
    }

    for (uint32_t i = 0; i < numElements; i++) {
        uintptr_t objPtr = m_dumper.getobj(static_cast<int>(i));
        if (!UE5DfmDumper::ok(objPtr)) continue;
        std::string cn = readObjClassName(m_dumper, objPtr);
        if (cn == "Class") classes.push_back(objPtr);
        else if (cn == "ScriptStruct") structs.push_back(objPtr);
        else if (cn == "Enum" || cn == "UserDefinedEnum") enums.push_back(objPtr);
    }

    LOG(LOG_LEVEL_INFO, "[UE5Header] 类型数量: Class=%zu ScriptStruct=%zu Enum=%zu",
        classes.size(), structs.size(), enums.size());

    // ── 前向声明 ──
    fout << "// ===========================================================\n";
    fout << "// Forward Declarations\n";
    fout << "// ===========================================================\n\n";

    for (auto objPtr : classes) {
        std::string name = cleanIdentifier(m_dumper.oname(objPtr));
        fout << "struct " << name << ";\n";
    }
    for (auto objPtr : structs) {
        std::string name = cleanIdentifier(m_dumper.oname(objPtr));
        fout << "struct " << name << ";\n";
    }
    fout << "\n";

    // ── 枚举 ──
    fout << "// ===========================================================\n";
    fout << "// Enums\n";
    fout << "// ===========================================================\n\n";

    for (auto objPtr : enums) {
        std::string name = cleanIdentifier(m_dumper.oname(objPtr));

        // UEnum::Names TArray 在 +0x40
        uintptr_t namesData = UE5DfmDumper::rp(objPtr + offsetof(UEnum, Names));
        int32_t   namesNum  = UE5DfmDumper::rs32(objPtr + offsetof(UEnum, Names) + 8);

        fout << "enum " << name << " {\n";
        if (UE5DfmDumper::ok(namesData) && namesNum > 0 && namesNum < 10000) {
            for (int i = 0; i < namesNum; i++) {
                uintptr_t entry = namesData + static_cast<uintptr_t>(i) * sizeof(FEnumNamePair);
                // FName 位于 entry+0x00, 借用 ffname 需减去其内部偏移以对齐
                std::string eName = m_dumper.ffname(entry - offsetof(FField, NamePrivate));
                // 读取 int64 值
                int64_t value = 0;
                uint32_t lo = UE5DfmDumper::r32(entry + 8);
                uint32_t hi = UE5DfmDumper::r32(entry + 12);
                value = (static_cast<int64_t>(hi) << 32) | lo;

                fout << "    " << cleanIdentifier(eName) << " = " << static_cast<long long>(value);
                if (i + 1 < namesNum) fout << ",";
                fout << "\n";
            }
        }
        fout << "};\n\n";
    }

    // 辅助 lambda: 遍历 UStruct 的属性 (ChildProperties, FField 链表)
    auto writeProperties = [&](std::ofstream& out, uintptr_t structPtr) {
        uintptr_t prop = UE5DfmDumper::rp(structPtr + offsetof(UStruct, ChildProperties));
        int depth = 0;
        while (UE5DfmDumper::ok(prop) && depth < 5000) {
            std::string cc = m_dumper.ffclassname(prop);
            if (cc.size() > 8 && cc.substr(cc.size() - 8) == "Property") {
                std::string fieldName = cleanIdentifier(m_dumper.ffname(prop));
                int32_t offsetInternal = UE5DfmDumper::rs32(prop + offsetof(FPropertyFlat, Offset_Internal));
                int32_t elementSize    = UE5DfmDumper::rs32(prop + offsetof(FPropertyFlat, ElementSize));
                const char* mappedType = mapPropertyToType(cc);
                std::string typeName = mappedType ? mappedType : cc.substr(0, cc.size() - 8);

                out << "    " << typeName << " " << fieldName << "; /* 0x"
                    << std::hex << offsetInternal << std::dec
                    << " Size: 0x" << std::hex << elementSize << std::dec << " */\n";
            }
            prop = UE5DfmDumper::rp(prop + offsetof(FField, Next));
            depth++;
        }
    };

    // ── ScriptStruct ──
    fout << "// ===========================================================\n";
    fout << "// ScriptStructs (Fields)\n";
    fout << "// ===========================================================\n\n";

    for (auto objPtr : structs) {
        std::string name = cleanIdentifier(m_dumper.oname(objPtr));
        int32_t propertiesSize = UE5DfmDumper::rs32(objPtr + offsetof(UStruct, PropertiesSize));
        uintptr_t superStruct  = UE5DfmDumper::rp(objPtr + offsetof(UStruct, SuperStruct));

        std::string superName;
        if (UE5DfmDumper::ok(superStruct)) {
            superName = cleanIdentifier(m_dumper.oname(superStruct));
        }

        fout << "// Size: 0x" << std::hex << propertiesSize << std::dec << "\n";
        fout << "struct " << name << " {\n";
        if (!superName.empty()) {
            int32_t superSize = UE5DfmDumper::rs32(superStruct + offsetof(UStruct, PropertiesSize));
            if (superSize <= 0) superSize = 8;
            fout << "    char _base_" << superName << "[0x" << std::hex << superSize << std::dec
                 << "]; /* 0x0 base: " << superName << " */\n";
        }
        writeProperties(fout, objPtr);
        fout << "};\n\n";
    }

    // ── Classes ──
    fout << "// ===========================================================\n";
    fout << "// Classes\n";
    fout << "// ===========================================================\n\n";

    for (auto objPtr : classes) {
        std::string name = cleanIdentifier(m_dumper.oname(objPtr));
        int32_t propertiesSize = UE5DfmDumper::rs32(objPtr + offsetof(UStruct, PropertiesSize));
        uintptr_t superStruct  = UE5DfmDumper::rp(objPtr + offsetof(UStruct, SuperStruct));

        std::string superName;
        if (UE5DfmDumper::ok(superStruct)) {
            superName = cleanIdentifier(m_dumper.oname(superStruct));
        }

        fout << "// Size: 0x" << std::hex << propertiesSize << std::dec << "\n";
        fout << "struct " << name << " {\n";

        if (!superName.empty()) {
            int32_t superSize = UE5DfmDumper::rs32(superStruct + offsetof(UStruct, PropertiesSize));
            if (superSize <= 0) superSize = 0x28;
            fout << "    char _base_" << superName << "[0x" << std::hex << superSize << std::dec
                 << "]; /* 0x0 base: " << superName << " */\n";
        } else {
            fout << "    void* _vptr; /* 0x0 */\n";
        }

        writeProperties(fout, objPtr);
        fout << "};\n\n";

        // Native 函数声明 (UFunction 在 Children 链表中, UField::Next = +0x28)
        uintptr_t child = UE5DfmDumper::rp(objPtr + offsetof(UStruct, Children));
        int depth = 0;
        bool hasNativeFunc = false;
        while (UE5DfmDumper::ok(child) && depth < 5000) {
            std::string cc = readObjClassName(m_dumper, child);
            if (cc == "Function") {
                uintptr_t func    = UE5DfmDumper::rp(child + offsetof(UFunction, Func));
                uint32_t funcFlags = UE5DfmDumper::r32(child + offsetof(UFunction, FunctionFlags));
                if (UE5DfmDumper::ok(func) && (funcFlags & FUNC_Native)) {
                    if (!hasNativeFunc) {
                        fout << "// " << name << " Methods\n";
                        hasNativeFunc = true;
                    }
                    std::string funcName = cleanIdentifier(m_dumper.oname(child));
                    uintptr_t offset = func - m_dumper.getModuleBase();
                    fout << "void " << name << "__" << funcName
                         << "(struct " << name << "* __this); /* RVA: 0x"
                         << std::hex << offset << std::dec << " */\n";
                }
            }
            child = UE5DfmDumper::rp(child + offsetof(UField, Next));
            depth++;
        }
        if (hasNativeFunc) fout << "\n";
    }

    fout << "// ===========================================================\n";
    fout << "// Summary\n";
    fout << "// ===========================================================\n";
    fout << "// Classes: " << classes.size() << "\n";
    fout << "// ScriptStructs: " << structs.size() << "\n";
    fout << "// Enums: " << enums.size() << "\n\n";

    fout << "#pragma pack(pop)\n";
    fout << "#endif // UE5_IDA_HEADER_H\n";
    fout.close();
    LOG(LOG_LEVEL_INFO, "[UE5Header] IDA 头文件完成: %s", path.c_str());
}

// =====================================================================
//  IDA Script JSON 生成
// =====================================================================

void UE5Header::saveToScriptJson(const std::string& path) {
    LOG(LOG_LEVEL_INFO, "[UE5Header] 生成 IDA 脚本 JSON: %s", path.c_str());

    std::ofstream fout(path, std::ios::out | std::ios::trunc);
    if (!fout.is_open()) {
        LOG(LOG_LEVEL_ERROR, "[UE5Header] 无法创建文件: %s", path.c_str());
        return;
    }

    struct FuncEntry {
        uintptr_t rva;
        std::string name;
        std::string signature;
    };
    std::vector<FuncEntry> entries;

    uint32_t numElements = UE5DfmDumper::r32(
        m_dumper.getModuleBase() + m_dumper.getOffGUObjectArrayNum());
    if (numElements == 0 || numElements > 20000000u) {
        LOG(LOG_LEVEL_ERROR, "[UE5Header] 无效的 numElements: %u", numElements);
        fout.close();
        return;
    }

    uintptr_t base = m_dumper.getModuleBase();

    for (uint32_t i = 0; i < numElements; i++) {
        uintptr_t objPtr = m_dumper.getobj(static_cast<int>(i));
        if (!UE5DfmDumper::ok(objPtr)) continue;
        std::string cn = readObjClassName(m_dumper, objPtr);
        if (cn != "Class" && cn != "ScriptStruct") continue;

        std::string className = m_dumper.oname(objPtr);

        uintptr_t child = UE5DfmDumper::rp(objPtr + offsetof(UStruct, Children));
        int depth = 0;
        while (UE5DfmDumper::ok(child) && depth < 5000) {
            std::string ccn = readObjClassName(m_dumper, child);
            if (ccn == "Function") {
                uintptr_t func = UE5DfmDumper::rp(child + offsetof(UFunction, Func));
                if (UE5DfmDumper::ok(func) && func > base) {
                    std::string funcName = m_dumper.oname(child);

                    FuncEntry e;
                    e.rva = func - base;
                    e.name = className + "$$" + funcName;
                    e.signature = "void " + cleanIdentifier(className) + "_"
                                + cleanIdentifier(funcName)
                                + "(struct " + cleanIdentifier(className) + "* __this);";
                    entries.push_back(e);
                }
            }
            child = UE5DfmDumper::rp(child + offsetof(UField, Next));
            depth++;
        }
    }

    LOG(LOG_LEVEL_INFO, "[UE5Header] 收集到 %zu 个函数", entries.size());

    std::sort(entries.begin(), entries.end(),
        [](const FuncEntry& a, const FuncEntry& b) { return a.rva < b.rva; });

    fout << "{\n";

    fout << "  \"ScriptMethod\": [\n";
    for (size_t i = 0; i < entries.size(); i++) {
        fout << "    {\n";
        fout << "      \"Address\": " << entries[i].rva << ",\n";
        fout << "      \"Name\": \"" << escapeJsonString(entries[i].name) << "\",\n";
        fout << "      \"Signature\": \"" << escapeJsonString(entries[i].signature) << "\"\n";
        fout << "    }";
        if (i + 1 < entries.size()) fout << ",";
        fout << "\n";
    }
    fout << "  ],\n";

    fout << "  \"Addresses\": [\n";
    for (size_t i = 0; i < entries.size(); i++) {
        fout << "    " << entries[i].rva;
        if (i + 1 < entries.size()) fout << ",";
        fout << "\n";
    }
    fout << "  ]\n";

    fout << "}\n";
    fout.close();
    LOG(LOG_LEVEL_INFO, "[UE5Header] IDA 脚本 JSON 完成: %s (%zu entries)",
        path.c_str(), entries.size());
}

} // namespace ue5dfm
